language: c

compiler:
  - gcc

sudo: false
 
addons:
  apt:
    packages:      
      - libaio-dev
      - libfuse-dev
      - cloc

before_install:
  - make
  - chmod +x unittest.sh

script: ./unittest.sh
