language: c

compiler:
  - gcc
  - clang

sudo: false
 
addons:
  apt:
    packages:      
      - libaio-dev
      - libfuse-dev

before_install:
  - make
  - chmod +x unittest.sh

#script: ./unittest.sh
