language: c

compiler:
  - gcc

sudo: false
 
addons:
  apt:
    packages:      
      - libaio-dev
      - libfuse-dev
      - cloc

before_install:
  - git clone https://github.com/spdk/spdk.git
  - pushd spdk
  - wget http://fast.dpdk.org/rel/dpdk-16.11.tar.xz
  - tar xf dpdk-16.11.tar.xz
  - pushd dpdk-16.11
  - make config T=x86_64-native-linuxapp-$CC
  - sed -i s/CONFIG_RTE_EAL_IGB_UIO=y/CONFIG_RTE_EAL_IGB_UIO=n/ build/.config
  - sed -i s/CONFIG_RTE_KNI_KMOD=y/CONFIG_RTE_KNI_KMOD=n/ build/.config
  - make
  - make install DESTDIR=.
  - export DPDK_DIR=$PWD/usr/local/share/dpdk/x86_64-native-linuxapp-$CC
  - popd
  - make DPDK_DIR=./dpdk-16.11/x86_64-native-linuxapp-gcc
  - popd
  - make SPDK_ROOT_DIR=spdk DPDK_DIR=spdk/dpdk-16.11/x86_64-native-linuxapp-gcc 
  - chmod +x unittest.sh

script: ./unittest.sh
